env:
  browser: true
  es6: true
  node: true
extends:
  - eslint:recommended
  - google
parserOptions:
  ecmaVersion: 2021
  sourceType: module
root: true
rules:
  arrow-parens:
    - error
    - always
  complexity:
    - error
    - max: 5
  max-len:
    - error
    - code: 80
  object-curly-spacing:
    - error
    - always
    - objectsInObjects: false
  require-jsdoc: 0
