env:
  browser: true
  node: true
extends:
  - eslint:recommended
parserOptions:
  ecmaVersion: latest
  sourceType: module
root: true
rules:
  array-bracket-newline: 0
  array-bracket-spacing:
    - error
    - never
  array-element-newline: 0
  arrow-parens:
    - error
    - always
  block-spacing:
    - error
    - never
  brace-style: error
  camelcase:
    - error
    - properties: never
  comma-dangle:
    - error
    - always-multiline
  comma-spacing: error
  comma-style: error
  complexity:
    - error
    - max: 5
  computed-property-spacing: error
  constructor-super: error
  curly:
    - error
    - multi-line
  eol-last: error
  func-call-spacing: error
  generator-star-spacing:
    - error
    - after
  guard-for-in: error
  indent:
    - error
    - 2
    - CallExpression:
        arguments: 2
      FunctionDeclaration:
        body: 1
        parameters: 2
      FunctionExpression:
        body: 1
        parameters: 2
      MemberExpression: 2
      ObjectExpression: 1
      SwitchCase: 1
      ignoredNodes:
        - ConditionalExpression
  key-spacing: error
  keyword-spacing: error
  linebreak-style:
    - error
    - unix
  max-len:
    - error
    - code: 80
      ignoreUrls: true
  new-cap: error
  no-array-constructor: error
  no-caller: error
  no-cond-assign: 0
  no-extend-native: error
  no-extra-bind: error
  no-invalid-this: error
  no-irregular-whitespace: error
  no-mixed-spaces-and-tabs: error
  no-multi-spaces: error
  no-multi-str: error
  no-multiple-empty-lines:
    - error
    - max: 2
  no-new-object: error
  no-new-symbol: error
  no-new-wrappers: error
  no-tabs: error
  no-this-before-super: error
  no-throw-literal: error
  no-trailing-spaces: error
  no-unexpected-multiline: error
  no-unused-vars:
    - error
    - args: none
  no-var: error
  no-with: error
  object-curly-spacing:
    - error
    - always
    - arraysInObjects: false
      objectsInObjects: false
  one-var:
    - error
    - const: never
      let: never
      var: never
  operator-linebreak:
    - error
    - after
  padded-blocks:
    - error
    - never
  prefer-arrow-callback:
    - error
  prefer-const:
    - error
    - destructuring: all
  prefer-promise-reject-errors: error
  prefer-rest-params: error
  prefer-spread: error
  quote-props:
    - error
    - consistent
  quotes:
    - error
    - single
    - allowTemplateLiterals: true
  rest-spread-spacing: error
  semi:
    - error
    - never
  semi-spacing: error
  space-before-blocks: error
  space-before-function-paren:
    - error
    - anonymous: never
      asyncArrow: always
      named: never
  spaced-comment:
    - error
    - always
  switch-colon-spacing: error
  valid-jsdoc:
    - error
    - prefer:
        returns: return
      requireParamDescription: false
      requireReturn: false
      requireReturnDescription: false
  yield-star-spacing:
    - error
    - after
