runtime: python27
api_version: 1
threadsafe: true

handlers:
# Let’s Encrypt verification.
- url: /.well-known/acme-challenge/(.+)
  static_files: .challenge/\1
  upload: .challenge/(.+)
  mime_type: text/plain
  secure: optional

# Service worker.
- url: /js/service-worker\.js
  static_files: public/js/service-worker.js
  upload: public/js/service-worker\.js
  secure: always
  http_headers:
    Service-Worker-Allowed: /

# Handle folder indexes.
- url: /(.*)/
  static_files: public/\1/index.html
  upload: public/(.*)/index\.html
  secure: always

# Handle root index.
- url: /
  static_files: public/index.html
  upload: public/index\.html
  secure: always

# Serve public folder.
- url: /
  static_dir: public/
  secure: always

skip_files:
- ^\.git$
- ^\.gitignore$
- ^package.json$
- ^README.md$
