options:
  env:
    - NODE_ENV=production
steps:
  - name: node:18-alpine
    args:
      - npm
      - install
      - --no-audit
      - --no-fund
      - --no-progress
  - name: node:18-alpine
    args:
      - npm
      - run
      - build
  - name: google/cloud-sdk:alpine
    dir: src
    args:
      - gcloud
      - app
      - deploy
      - app.yaml
      - cron.yaml
      - index.yaml
      - --promote
      - --quiet
