options:
  env:
    - NODE_ENV=production
steps:
  - name: node:14-alpine
    dir: static
    args:
      - npm
      - clean-install
  - name: node:14-alpine
    dir: static
    args:
      - npm
      - run
      - build
    volumes:
      - name: static
        path: /workspace/static/build
  - name: python:3.9-slim
    dir: django
    args:
      - pip
      - install
      - --requirement=requirements.txt
      - --user
    volumes:
      - name: static
        path: /workspace/django/static
  - name: python:3.9-slim
    dir: django
    args:
      - python
      - manage.py
      - collectstatic
      - --no-input
    volumes:
      - name: static
        path: /workspace/django/static
  - name: google/cloud-sdk:alpine
    dir: django
    args:
      - gcloud
      - app
      - deploy
      - app.yaml
      - cron.yaml
      - index.yaml
      - --version=live
      - --no-promote
      - --quiet
    volumes:
      - name: static
        path: /workspace/django/static
