options:
  env:
    - NODE_ENV=production
steps:
  - name: node:14-alpine
    entrypoint: npm
    args:
      - ci
  - name: node:14-alpine
    entrypoint: npm
    args:
      - run
      - build
  - name: node:14-alpine
    entrypoint: npx
    args:
      - firebase-tools
      - deploy
