runtime: python37

automatic_scaling:
  max_instances: 1
  min_instances: 1

env_variables:
  DJANGO_ALLOWED_HOSTS: '*'

handlers:
  - url: /static
    static_dir: static
  - url: /.*
    script: auto
