name: Build

on:
  push:
    branches:
      - main

env:
  NODE_ENV: production

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Checkout content
        uses: actions/checkout@v4
        with:
          path: content
          repository: liamnewmarch/blog-posts
          token: ${{ secrets.TOKEN }}
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          cache: npm
          node-version: 22
      - name: Install
        run: npm ci
      - name: Build
        run: npm run build
      - name: Copy
        run: mkdir -p /mnt/build && cp -r build /mnt
