name: Build and deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          cache: npm
          node-version: 22
      - name: Install
        run: npm ci
      - name: Build
        run: npm run build
      - name: Deploy
        run: rsync -aghoz --info=stats --chown=${{ secrets.DEPLOY_USER }}:${{ secrets.DEPLOY_GROUP }} build/ ${{ secrets.DEPLOY_PATH }}
